spring.datasource.url=jdbc:postgresql://localhost:5432/SE
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

cloudinary.cloud-name=drcetd9mw
cloudinary.api-key=624791611391871
cloudinary.api-secret=3HeBdB7RgNi3jix1C6HOLwJIlZE